#!/bin/bash -u

# omega API engine
# http://code.google.com/p/theomega/
# 
# Copyright 2011, Jonathon Fillmore
# Licensed under the MIT license. See LICENSE file.
# http://www.opensource.org/licenses/mit-license.php

BASE_DIR=$(cd $(dirname "$0") && pwd -P)

js_dir="$BASE_DIR/common/js"
css_dir="$BASE_DIR/common/css"

$BASE_DIR/gen_gui omega \
	--compiler ~/scripts/compiler.jar \
	--opt WHITESPACE_ONLY \
	--js-dir "$js_dir" \
	--css-dir "$css_dir" \
	--js $js_dir/core.js \
	--js $js_dir/sprintf.js \
	--js $js_dir/json.js \
	--js $js_dir/Test.class.js \
	--js $js_dir/BoxFactory.class.js \
	--js $js_dir/OmegaClient.class.js \
	--js $js_dir/ColorFactory.class.js \
	--js $js_dir/Visualizer.class.js \
	--js $js_dir/DataShed.class.js \
	--css $css_dir/BoxFactory.class.css 
