#!/usr/bin/env python

# omega - python client
# https://github.com/jfillmore/Omega-API-Engine
# 
# Copyright 2011, Jonathon Fillmore
# Licensed under the MIT license. See LICENSE file.
# http://www.opensource.org/licenses/mit-license.php

import sys
import omega.shell

shell = omega.shell.Shell(sys.argv[1:])
sys.exit(shell.last_rv)
