/* omega - js lib
   http://code.google.com/p/theomega/
  
   Copyright 2011, Jonathon Fillmore
   Licensed under the MIT license. See LICENSE file.
   http://www.opensource.org/licenses/mit-license.php */

var om={};
(function(om){om.subtract=function(f1,f2){var sig_digs,d1,d2;d1=String(f1).match(/\.[0-9]+$/);d2=String(f2).match(/\.[0-9]+$/);if(d1)d1=d1[0].length-1;else d1=0;if(d2)d2=d2[0].length-1;else d2=0;sig_digs=Math.max(d1,d2);return om.round(f1-f2,{decimal:sig_digs})};om.ucfirst=function(str){return str.substr(0,1).toUpperCase()+str.substr(1,str.length-1)};om.lcfirst=function(str){return str.substr(0,1).toLowerCase()+str.substr(1,str.length-1)};om.flatten=function(str,add_cap_gap){str=str.substr(0,1).toLowerCase()+
str.substr(1);if(add_cap_gap===true)str=str.replace(/([A-Z])/g,"_$1");return str.toLowerCase().replace(/( |_)+/g,"_").replace(/[^a-z0-9_]+/g,"")};om.is_jquery=function(obj){return typeof obj==="object"&&obj.length!==undefined&&obj.jquery!==undefined};om.is_numeric=function(str){return!isNaN(parseFloat(str))&&isFinite(str)};om.isnt_numeric=function(str){return!om.is_numeric(str)};om.plural=function(obj){var item;for(item in obj)if(obj.hasOwnProperty(item))return true;return false};om.link_event=function(event_type,
from_obj,to_obj){from_obj.bind(event_type,function(e){to_obj.trigger(event_type,e)})};om.reflect_event=function(event_type,from_obj,to_obj){from_obj.bind(event_type,function(e){to_obj.trigger(event_type,e);event_type.preventDefault();event_type.stopPropagation()})};om.assemble=function(type,attributes,inner_html,leave_open){if(!type.match(/^[a-zA-Z]+/))throw new Error('Invalid object type: "'+type+'".');var value,name,html="<"+type;for(name in attributes)if(attributes.hasOwnProperty(name)){value=
"";if(jQuery.isArray(attributes[name]))value=attributes[name].join(" ");else if(attributes[name]===null||attributes[name]===undefined)value="";else if(typeof attributes[name]==="object")throw new Error("Unable to assemble object '"+name+"' into attributes.");else value=String(attributes[name]);html+=" "+name+'="'+value.replace(/"/,'\\"')+'"'}html+=">";if(inner_html!==undefined)html+=inner_html;if(leave_open===undefined)leave_open=false;if(!leave_open)html+="</"+type+">";return html};om.set_cookie=
function(name,value,ttl){if(value===undefined||value===null)value="";var expiration,cookie=name+"="+om.json.encode(value).replace(/; /g,"\\; \\ ");if(typeof ttl==="number"){expiration=new Date;expiration.setDate(expiration.getDate()+ttl);cookie+=";expires="+expiration.toGMTString()}else if(ttl!==undefined)throw new Error("Invalid TTL ("+typeof ttl+"): "+String(ttl)+".");document.cookie=cookie};om.get_cookies=function(){var cookies={},dough,index,value,cookie_name,i;if(document.cookie==="")return[];
dough=document.cookie.split("; ");for(i=0;i<dough.length;i+=1){index=dough[i].indexOf("=");cookie_name=dough[i].substr(0,index);if(index+1>=dough[i].length)cookies[cookie_name]="";else cookies[cookie_name]=dough[i].substr(index+1).replace(/\; \ /g,"; ")}return cookies};om.get_cookie=function(name,decode){var cookies=om.get_cookies();if(name in cookies)if(decode)return om.json.decode(cookies[name]);else return cookies[name]};om.delete_cookie=function(name){};om.delete_cookies=function(re){};om.find_cookies=
function(re,decode){var matches=[],cookies=om.get_cookies(),name;for(name in cookies)if(cookies.hasOwnProperty(name))if(re.test(name))if(decode)matches.push(om.json.decode(cookies[name]));else matches.push(cookies[name]);return matches};om.round=function(num,args){var mod,int_half,multiplier,i,to_add;if(args===undefined)args={};if(args.interval!==undefined&&args.decimal!==undefined)throw new Error("Unable to use both the 'interval' and 'decimal' options.");if(args.interval){mod=Math.abs(num)%args.interval;
if(args.floor)if(num>0)num-=mod;else num-=args.interval-mod;else if(args.ceiling&&mod!==0)if(num>0)num+=args.interval-mod;else num+=mod;else{int_half=args.interval/2;if(mod>=int_half)if(num>0)num+=args.interval-mod;else num-=args.interval-mod;else if(num>0||args.ceiling)num-=mod;else num+=mod}}else{multiplier=Math.pow(10,args.decimal?args.decimal:0);if(args.decimal)num*=multiplier;if(args.ceiling&&num%1)num+=0.5;else if(args.floor&&num%1)num-=0.5;num=Math.round(num);if(args.decimal)num/=multiplier;
if(args.min_dec!==undefined){num=String(num);to_add=num.match(/\.(.*)$/);if(to_add!==null){to_add=args.min_dec-to_add[1].length;for(i=0;i<to_add;i++)num+="0"}}}return num};om.Error=function(message,args){var error;if(args===undefined)args={};if(args.modal===undefined)args.modal=true;if(args.title===undefined)args.title="Error";if(args.target===undefined)args.target=$("body");error=om.bf.make.confirm(args.target,args.title,message,{modal:args.modal,on_close:args.on_close});if(args.bt!==undefined){error.details=
error._box_middle._add_box("om_error_backtrace");error.details.title=error.details._add_box("om_error_title");error.details.title.$.html("Details");error.details.bt=error.details._add_box("om_error_bt");error.details.bt.$.html(om.vis.obj2html(args.bt))}error.message=message;error._args=args;error._add_retry=function(func_args){error._box_bottom._add_input("button","retry",{caption:"Re-try",multi_click:true,on_click:function(button_click){error._remove();if(func_args!==undefined)func_args.callee.apply(this,
func_args)}})};if(args.retry!==undefined)error._add_retry(args.retry);error._raise();return error};om.error=om.Error;return om})(om);
(function(om){om.sprintf=function(){var str_format;function get_type(variable){return Object.prototype.toString.call(variable).slice(8,-1).toLowerCase()}function str_repeat(input,multiplier){for(var output=[];multiplier>0;output[--multiplier]=input);return output.join("")}str_format=function(){if(!str_format.cache.hasOwnProperty(arguments[0]))str_format.cache[arguments[0]]=str_format.parse(arguments[0]);return str_format.format.call(null,str_format.cache[arguments[0]],arguments)};str_format.format=
function(parse_tree,argv){var cursor=1,tree_length=parse_tree.length,node_type="",arg,output=[],i,k,match,pad,pad_character,pad_length;for(i=0;i<tree_length;i++){node_type=get_type(parse_tree[i]);if(node_type==="string")output.push(parse_tree[i]);else if(node_type==="array"){match=parse_tree[i];if(match[2]){arg=argv[cursor];for(k=0;k<match[2].length;k++){if(!arg.hasOwnProperty(match[2][k]))throw om.sprintf('[sprintf] property "%s" does not exist',match[2][k]);arg=arg[match[2][k]]}}else if(match[1])arg=
argv[match[1]];else arg=argv[cursor++];if(/[^s]/.test(match[8])&&get_type(arg)!="number")throw om.sprintf("[sprintf] expecting number but found %s",get_type(arg));switch(match[8]){case "b":arg=arg.toString(2);break;case "c":arg=String.fromCharCode(arg);break;case "d":arg=parseInt(arg,10);break;case "e":arg=match[7]?arg.toExponential(match[7]):arg.toExponential();break;case "f":arg=match[7]?parseFloat(arg).toFixed(match[7]):parseFloat(arg);break;case "o":arg=arg.toString(8);break;case "s":arg=(arg=
String(arg))&&match[7]?arg.substring(0,match[7]):arg;break;case "u":arg=Math.abs(arg);break;case "x":arg=arg.toString(16);break;case "X":arg=arg.toString(16).toUpperCase();break}arg=/[def]/.test(match[8])&&match[3]&&arg>=0?"+"+arg:arg;pad_character=match[4]?match[4]=="0"?"0":match[4].charAt(1):" ";pad_length=match[6]-String(arg).length;pad=match[6]?str_repeat(pad_character,pad_length):"";output.push(match[5]?arg+pad:pad+arg)}}return output.join("")};str_format.cache={};str_format.parse=function(fmt){var _fmt=
fmt,match=[],parse_tree=[],arg_names=0;while(_fmt){if((match=/^[^\x25]+/.exec(_fmt))!==null)parse_tree.push(match[0]);else if((match=/^\x25{2}/.exec(_fmt))!==null)parse_tree.push("%");else if((match=/^\x25(?:([1-9]\d*)\$|\(([^\)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosuxX])/.exec(_fmt))!==null){if(match[2]){arg_names|=1;var field_list=[],replacement_field=match[2],field_match=[];if((field_match=/^([a-z_][a-z_\d]*)/i.exec(replacement_field))!==null){field_list.push(field_match[1]);while((replacement_field=
replacement_field.substring(field_match[0].length))!=="")if((field_match=/^\.([a-z_][a-z_\d]*)/i.exec(replacement_field))!==null)field_list.push(field_match[1]);else if((field_match=/^\[(\d+)\]/.exec(replacement_field))!==null)field_list.push(field_match[1]);else throw"[sprintf] huh?";}else throw"[sprintf] huh?";match[2]=field_list}else arg_names|=2;if(arg_names===3)throw"[sprintf] mixing positional and named placeholders is not (yet) supported";parse_tree.push(match)}else throw"[sprintf] huh?";_fmt=
_fmt.substring(match[0].length)}return parse_tree};return str_format}();om.vsprintf=function(fmt,argv){argv.unshift(fmt);return om.sprintf.apply(null,argv)}})(om);
(function(om){om.JSON={};om.JSON.auto_complete=function(json,encode){var i,queue=[],chr,next_expected=null;for(i=0;i<json.length;i++){chr=json[i];if(next_expected!==null&&chr!==next_expected)continue;if(chr==="\\")continue;if(chr==="{"){queue.push(chr);next_expected=null}else if(chr==="["){queue.push(chr);next_expected=null}else if(chr==='"')if(queue[queue.length-1]==='"'){if(next_expected===chr)next_expected=null;queue.pop()}else{queue.push(chr);next_expected=chr}else if(chr==="}")if(queue[queue.length-
1]==="{")queue.pop();else throw new Error("JSON auto-complete parse error on character '"+chr+"' (#"+i+").");else if(chr==="]")if(queue[queue.length-1]==="[")queue.pop();else throw new Error("JSON auto-complete parse error on character '"+chr+"' (#"+i+").");}for(i=queue.length-1;i>=0;i--){chr=queue[i];if(chr==="{")json+="}";else if(chr==="[")json+="]";else if(chr==='"')json+='"';else throw new Error("Unrecognized token in JSON auto-complete: '"+chr+"'.");}if(encode===true)return om.JSON.encode(json);
else return json};function f(n){return n<10?"0"+n:n}if(typeof Date.prototype.decode!=="function"){Date.prototype.decode=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null};String.prototype.decode=Number.prototype.decode=Boolean.prototype.decode=function(key){return this.valueOf()}}var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+string+'"'}function str(key,holder){var i,
k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==="object"&&typeof value.decode==="function")value=value.decode(key);if(typeof rep==="function")value=rep.call(holder,key,value);switch(typeof value){case "string":return quote(value);case "number":return isFinite(value)?String(value):"null";case "boolean":case "null":return String(value);case "object":if(!value)return"null";gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==="[object Array]"){length=value.length;
for(i=0;i<length;i+=1)partial[i]=str(i,value)||"null";v=partial.length===0?"[]":gap?"[\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"]":"["+partial.join(",")+"]";gap=mind;return v}if(rep&&typeof rep==="object"){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==="string"){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}}}else for(k in value)if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}v=partial.length===0?"{}":gap?"{\n"+gap+
partial.join(",\n"+gap)+"\n"+mind+"}":"{"+partial.join(",")+"}";gap=mind;return v}}if(typeof om.JSON.encode!=="function")om.JSON.encode=function(value,replacer,space){var i;gap="";indent="";if(typeof space==="number")for(i=0;i<space;i+=1)indent+=" ";else if(typeof space==="string")indent=space;rep=replacer;if(replacer&&typeof replacer!=="function"&&(typeof replacer!=="object"||typeof replacer.length!=="number"))throw new Error("om.JSON.encode");return str("",{"":value})};if(typeof om.JSON.decode!==
"function")om.JSON.decode=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==="object")for(k in value)if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined)value[k]=v;else delete value[k]}return reviver.call(holder,key,value)}cx.lastIndex=0;if(cx.test(text))text=text.replace(cx,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+text+")");return typeof reviver==="function"?walk({"":j},""):j}throw new SyntaxError("om.JSON.decode");};om.json=om.JSON})(om);(function(om){om["Test"]={hostname_re:/^([a-zA-Z0-9_-]+\.)*[a-zA-Z0-9-]+\.[a-zA-Z0-9\-]+$/,ip4_address_re:/^\d{1,3}(\.\d{1,3}){3}$/,email_address_re:/^[a-zA-Z0-9+._-]+@[a-zA-Z0-9+._\-]+$/,word_re:/^[a-zA-Z0-9_-]+$/};om.test=om.Test})(om);
(function(om){om.ColorFactory={};om.cf=om.ColorFactory;om.cf.get=function(color,args){var hue,result,i,rgb_clr,min,max,delta,tmp;if(color===undefined)throw new Error("Invalid color to get value of.");if(args===undefined)args={};if(args.format===undefined)args.format="hex";if(om.is_jquery(color)){if(args.surface===undefined)args.surface="color";color=color.css(args.surface)}if(typeof color==="string")if(color.match(/^#?[a-f0-9]{6}$/i)){if(color.substr(0,1)!=="#")color="#"+color;if(args.format==="hex")return color}else if(color.substr(0,
4)==="rgb("){if(args.format==="rgb")return color;color=color.substr(4,color.length-5).split(",");for(i=0;i<color.length;i++){color[i]=parseInt(color[i]).toString(16);if(color[i].length===1)color[i]="0"+color[i];else if(color[i].length>2)throw new Error("Color component '"+color[i]+"' is out of bounds.");}color="#"+color.join("")}else throw new Error("Invalid color string: '"+color+"'.");else if(typeof color==="object"){result="#";if(color.r!==undefined&&color.g!==undefined&&color.b!==undefined){if(args.format===
"rgb_obj")return color;color={r:color.r,g:color.g,b:color.b};for(hue in color)if(color.hasOwnProperty(hue)){color[hue]=color[hue].toString(16);if(color[hue].length===1)result+="0"+color[hue];else result+=color[hue]}}else if(color.h!==undefined&&color.s!==undefined&&color.v!==undefined){if(args.format==="hsv_obj")return color;if(color.s===0){color=String(parseInt(color.v*255,16));if(color.length===1)color="0"+color;color="#"+color+color+color}else{color.h=color.h%360/60;tmp={i:Math.floor(color.h)};
tmp.f=color.h-tmp.i;tmp.p=color.v*(1-color.s);tmp.q=color.v*(1-color.s*tmp.f);tmp.t=color.v*(1-color.s*(1-tmp.f));if(tmp.i===0)rgb_clr={r:color.v,g:tmp.t,b:tmp.p};else if(tmp.i===1)rgb_clr={r:tmp.q,g:color.v,b:tmp.p};else if(tmp.i===2)rgb_clr={r:tmp.p,g:color.v,b:tmp.t};else if(tmp.i===3)rgb_clr={r:tmp.p,g:tmp.q,b:color.v};else if(tmp.i===4)rgb_clr={r:tmp.t,g:tmp.p,b:color.v};else if(tmp.i===5)rgb_clr={r:color.v,g:tmp.p,b:tmp.q};else throw new Error("Invalid color hue: '"+color.h*60+"'.");result=
"#";for(hue in rgb_clr)if(rgb_clr.hasOwnProperty(hue)){rgb_clr[hue]=parseInt(rgb_clr[hue]*255,10).toString(16);if(rgb_clr[hue].length===1)result+="0"+rgb_clr[hue];else result+=rgb_clr[hue]}}}else throw new Error("Unrecognized color object.");color=result}else throw new Error("Unrecognized color type: "+color+".");if(args.format==="hex");else if(args.format==="rgb")color="rgb("+parseInt(color.substr(1,2),16)+", "+parseInt(color.substr(3,2),16)+", "+parseInt(color.substr(5,2),16)+")";else if(args.format===
"hsv_obj"){rgb_clr={"r":parseInt(color.substr(1,2),16)/255,"g":parseInt(color.substr(3,2),16)/255,"b":parseInt(color.substr(5,2),16)/255};max=Math.max(rgb_clr.r,rgb_clr.g,rgb_clr.b);min=Math.min(rgb_clr.r,rgb_clr.g,rgb_clr.b);delta=max-min;color={h:0,s:0,v:max};if(max!==0)color.s=delta/max;else return{s:0,h:360,v:color.v};if(rgb_clr.r===max)color.h=(rgb_clr.g-rgb_clr.b)/delta;else if(rgb_clr.g===max)color.h=2+(rgb_clr.b-rgb_clr.r)/delta;else color.h=4+(rgb_clr.r-rgb_clr.g)/delta;color.h*=60;if(color.h<
0)color.h+=360;color.h=parseInt(color.h,10)}else if(args.format==="rgb_obj")color={"r":parseInt(color.substr(1,2),16),"g":parseInt(color.substr(3,2),16),"b":parseInt(color.substr(5,2),16)};else throw new Error("Invalid color format: '"+args.format+"'.");return color};om.cf.make={fade:function(colors,args){var fade;if(args===undefined)args={};if(args.steps===undefined)args.steps=1;if(args.allow_oob===undefined)args.allow_oob=true;fade={_args:args,colors:[]};fade.set_steps=function(steps){if(typeof steps===
"number"&&steps>=0){fade.steps=steps;fade.size=(fade.colors.length-1)*fade.steps+fade.colors.length}else throw new Error("The number of steps must be 0 or greater.");};fade.set_size=function(count){if(count===fade.colors.length)fade.set_steps(0);else fade.set_steps((count-fade.colors.length)/(fade.colors.length-1))};fade.get_colors=function(args){var colors=[],i;if(args===undefined)args={};for(i=0;i<fade.size;i+=1)colors.push(fade.get_color(i),args);return colors};fade.set_colors=function(colors,
args){var i;if(args===undefined)args={};if(om.is_jquery(colors))if(args.surface===undefined)args.surface="color";fade.colors=[];if(!(jQuery.isArray(colors)||om.is_jquery(colors)))throw new Error("Invalid colors for fade; jQuery ref or array expected.");for(i=0;i<colors.length;i+=1)fade.colors[i]=om.cf.get(colors[i],args)};fade.get_color=function(i,args){var start_color_num,end_color_num,offset,blend_ratio,depth=0;if(args===undefined)args={};if(args.format===undefined)args.format="hex";if(i<0||i>=
fade.size)if(!fade._args.allow_oob)throw new Error("Please enter a color number between 0 and "+fade.size-1+".");else{if(i<0)i=i*-1;if(i>=fade.size){depth=parseInt(i/fade.size,10);if(depth%2===1)i=fade.size-i%fade.size-1;else i=i%fade.size}}start_color_num=parseInt(i/fade.size,10);end_color_num=start_color_num+1;offset=i%(fade.steps+2);blend_ratio=offset/(fade.steps+2);return om.cf.blend(fade.colors[start_color_num],fade.colors[end_color_num],{ratio:blend_ratio,format:args.format})};fade.set_colors(colors);
fade.set_steps(args.steps);return fade}};om.cf.blend=function(source,target,args){var color,part;if(args===undefined)args={};if(args.format===undefined)args.format="hex";if(args.ratio===undefined)args.ratio=0.5;source=om.cf.get(source,{format:"rgb_obj"});target=om.cf.get(target,{format:"rgb_obj"});if(args.ratio===0)color=source;else if(args.ratio===1)color=target;else{color={"r":parseInt(source.r*(1-args.ratio)+target.r*args.ratio,10),"g":parseInt(source.g*(1-args.ratio)+target.g*args.ratio,10),"b":parseInt(source.b*
(1-args.ratio)+target.b*args.ratio,10)};for(part in color)if(color.hasOwnProperty(part))if(parseInt(color[part],10)>255)color[part]=255;else if(parseInt(color[part],10)<0)color[part]=0}return om.cf.get(color,{format:args.format})};om.cf.mix=function(color,args){if(args===undefined)args={};color=om.cf.get(color,{format:"hsv_obj"});if(args.hue!==undefined)color.h=args.hue;else if(args.hue_shift!==undefined)color.h+=args.hue_shift;else if(args.hue_mult!==undefined)color.h*=args.hue_mult;else if(args.saturation!==
undefined)color.s=args.saturation;else if(args.saturation_shift!==undefined)color.s+=args.saturation_shift;else if(args.saturation_mult!==undefined)color.s*=args.saturation_mult;else if(args.value!==undefined)color.v=args.value;else if(args.value_shift!==undefined)color.v+=args.value_shift;else if(args.value_mult!==undefined)color.v*=args.value_mult;if(color.h<0)color.h=360+color.h%360;if(color.h>360)color.h=color.h%360;if(color.s>1)color.s=1;if(color.s<0)color.s=0;if(color.v>1)color.v=1;if(color.v<
0)color.v=0;return om.cf.get(color,args.format)}})(om);
(function(om){om.Visualizer={obj2html:function(data,args){var html="",data_type=typeof data,fade,key,str;if(args===undefined)args={};if(args.depth===undefined)args.depth=1;if(args.colors===undefined)args.colors=["#FFFFFF","#FF6000"];if(args.add_spaces===undefined)args.add_spaces=false;fade=om.cf.make.fade(args.colors,{steps:2});if(data_type==="undefined")html+='<span class="om_type_'+data_type+'">undefined</span>';else if(data===null)html+='<span class="om_type_'+data_type+'">null</span>';else if(data_type===
"object"&&data!==null)for(key in data){if(data.hasOwnProperty(key)){html+='<span class="om_object_key" style="color: '+fade.get_color(args.depth)+'; ">';if(args.add_spaces)html+=key.replace(/_/g," ");else html+=key;html+="</span>";if(typeof data[key]==="object"&&data[key]!==null){html+='<br/><div class="om_object_value" style="padding-left: 7px;">';html+=arguments.callee(data[key],{depth:args.depth+1,colors:args.colors,add_spaces:args.add_spaces});html+="</div>\n"}else{html+=": "+arguments.callee(data[key],
{colors:args.colors,add_spaces:args.add_spaces});html+="<br/>"}}}else{str=String(data).replace(/</g,"&lt;").replace(/>/g,"gt;");return'<span class="om_type_'+data_type+'">'+str+"</span>\n"}return html}};om.vis=om.Visualizer})(om);
(function(om){om.DataShed=function(om_client,args){var shed={_args:args,storage:{},enabled:true};if(args===undefined)args={};if(args.enabled===undefined)args.enabled=true;shed.enabled=args.enabled;shed.bind_service=function(om_client){shed.client=om_client};shed.clear_shed=function(){shed.storage={}};shed.forget=function(bin,key){delete shed.storage[bin][key]};shed.dump_bin=function(bin){delete shed.storage[bin]};shed.store=function(bin,key,value){if(bin in shed.storage)shed.storage[bin][key]=value;
else{shed.storage[bin]={};shed.storage[bin][key]=value}};shed.get_bin=function(bin){if(bin in shed.storage)return shed.storage[bin]};shed.get=function(bin,key){if(bin in shed.storage)if(key in shed.storage[bin])return shed.storage[bin][key]};shed.fetch=function(bin,key,api,params,on_complete,on_failure){if(shed.enabled&&bin in shed.storage&&key in shed.storage[bin])on_complete(shed.storage[bin][key]);else shed.client.exec(api,params,function(response){shed.store(bin,key,response);if(typeof on_complete===
"function")on_complete(response)},on_failure)};shed.fetch_na=function(bin,key,api,params,on_complete,on_failure){if(shed.enabled&&bin in shed.storage&&key in shed.storage[bin])on_complete(shed.storage[bin][key]);else shed.client.exec_na(api,params,function(response){shed.store(bin,key,response);if(typeof on_complete==="function")on_complete(response)},on_failure)};shed.bind_service(om_client);return shed};om.ds=om.DataShed})(om);

module.exports = om;
